// Generated by https://quicktype.io

export interface EventType {
    id: number;
    user_id: number;
    title: string;
    slug: string;
    tgl: Date;
    desc: string;
    image: string;
    views: number;
    created_at: Date;
    updated_at: Date;
    user: User;
}

export interface User {
    id: number;
    name: string;
    email: string;
    otp: null;
    expired_otp: null;
    tempat_lahir: null;
    tanggal_lahir: null;
    umur: null;
    phone: null;
    alamat: null;
    jk: null;
    role: string;
    bio: null;
    status: number;
    image: string;
    created_at: Date;
    updated_at: Date;
}
