// Generated by https://quicktype.io

export interface VideoType {
    id: number;
    section_id: number;
    title: string;
    type: string;
    description: null;
    url: URL;
    url_drive: null | string;
    file: null;
    duration: string;
    status: number;
    created_at: Date;
    updated_at: Date;
    section: Section;
}

export interface Section {
    id: number;
    kelas_id: number;
    title: string;
    total_video: number;
    total_duration: string;
    created_at: Date;
    updated_at: Date;
    kelas: Kelas;
}

export interface Kelas {
    id: number;
    level_id: number;
    type_id: number;
    category_id: number;
    user_id: number;
    title: string;
    slug: string;
    price: number;
    discount: number;
    description: string;
    body: string;
    benefit: Benefit[];
    link_overview: URL;
    image: string;
    status: string;
    views: number;
    created_at: Date;
    updated_at: Date;
    level: Category;
    type: Category;
    category: Category;
    user: User;
}

export enum Benefit {
    AksesSelamanya = "Akses selamanya",
    FleksibilitasWaktu = "Fleksibilitas Waktu",
    PelatihanBerkelanjutan = "Pelatihan Berkelanjutan",
}

export interface Category {
    id: number;
    name: Name;
    slug?: string;
    image?: string;
    created_at: Date;
    updated_at: Date;
}

export enum Name {
    Laravel = "Laravel",
    Pemula = "Pemula",
    Premium = "Premium",
}

export interface URL {
    url: string;
    embed_url: string;
    width: string;
    height: string;
    responsive: boolean;
    options: Options;
}

export interface Options {
    controls: string;
    nocookie: string;
    start: string;
}

export interface User {
    id: number;
    name: string;
    email: string;
    tempat_lahir: string;
    tanggal_lahir: Date;
    umur: number;
    phone: string;
    alamat: string;
    jk: string;
    role: string;
    bio: string;
    status: number;
    image: null;
    created_at: Date;
    updated_at: Date;
}
